version: "2"

linters:
  default: none
  enable:
    - loglint

  settings:
    custom:
      loglint:
        type: module
        description: Checks log message rules (lowercase, English, special chars, sensitive data)
        settings:
          require-lowercase-start: true
          require-english: true
          forbid-special-chars: true
          forbid-sensitive-data: true
          sensitive-keywords:
            - password
            - api_key
            - token
          sensitive-patterns:
            - (?i)secret\\s*[:=]
